### PR TITLE
adding clear output button. adding ability to grow/shrink the editor

### PR DESCRIPTION
**Pull request by shaunxcode**
I think the changes are pretty straight forward and I tried to make them in a way that was consistent with the existing codebase. However I did notice emacs decided to fix some trailing white space etc. without my direct consent - hopefully that is not an issue.

### CODE REVIEW

**Comment by jonase** [comment]
This looks awesome, thanks!

I'll take a closer look at this later today or tomorrow.

**Comment by jonase** [comment]
Great work!

How difficult would it be to grow/shrink the editor both horizontally and vertically? Also, is it possible to make the console stick to the bottom so it also grows/shrinks with the editor?

If you're interested in exploring these suggestions I'll be happy to accept more pull requests. Otherwise, I certainly will when I get some free time.

Thanks again!

**Comment by shaunxcode** [comment]
Not hard at all I will take a look tonight. It might mess up the bootstrap
stuff unless we have it snap to specific bs col widths?

I have some other ideas like having multiple namespaces open as different
tabs in one fiddle that I am playing with too.

**Comment by jonase** [comment]
Don't worry about bootstrap. I only used it to .. ehm .. bootstrap the UI :)

Open/close additional namespace tabs is a good idea (and something I've also been thinking about). It might require some backend changes depending on how we want to implement it.

**Pull request merged**
